#!/bin/sh
echo "Reloading services..."
# Use kickstart which works on both rooted and rootless jailbreaks
launchctl kickstart -k system/com.apple.appstored
launchctl kickstart -k system/com.apple.itunesstored
echo "Reloaded services."
exit 0