name: Build and Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup THEOS
      run: |
        brew install ldid make
        sudo git clone --recursive https://github.com/theos/theos.git /opt/theos
        echo "THEOS=/opt/theos" >> $GITHUB_ENV
        echo "PATH=/opt/theos/bin:$PATH" >> $GITHUB_ENV

    - name: Clean build directory
      run: |
        make clean || true

    - name: Build package
      run: |
        echo "Starting build..."
        make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
        echo "Build completed. Checking results..."
        ls -la packages/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: deb-package
        path: packages/*.deb

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: packages/*.deb
        draft: false
        prerelease: false
        generate_release_notes: true
        body: |
          ## NoAppThinning Release
          
          Cydia tweak to disable App Store app thinning on iOS 11+ devices.
          
          ### Installation
          Download the `.deb` file and install it with your package manager.
          
          ### Compatibility
          - iOS 11 and later
          - iPhone 7+ and newer devices (arm64, arm64e support)
          - Rootless jailbreaks (Dopamine, etc.)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
